# Generated by Django 5.0 on 2023-12-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_zapatillas_imagen_post'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='zapatillas',
        #     name='imagen',
        # ),
        migrations.AddField(
            model_name='zapatillas',
            name='imagen_url',
            field=models.URLField(default='https://ibb.co/qy1DD7Y'),
            preserve_default=False,
        ),
    ]
