# Generated by Django 5.0 on 2023-12-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_zapatillas_imagen_url'),
    ]

    operations = [
    ]
