# Generated by Django 5.0 on 2023-12-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20231224_1746'),
    ]

    operations = [
    ]
